# This file was generated by GoReleaser. DO NOT EDIT.
class GitCredentialSubstitute < Formula
  desc "git credential helper, which switches git credentials for the username/organization."
  homepage "https://github.com/sadayuki-matsuno/git-credential-substitute"
  version "0.1.7"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/sadayuki-matsuno/git-credential-substitute/releases/download/v0.1.7/git-credential-substitute_0.1.7_macOS-x86_64.tar.gz"
    sha256 "162866d990891835229bf333c22515e5914a2b514951e2cac416adc7ef1398ed"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/sadayuki-matsuno/git-credential-substitute/releases/download/v0.1.7/git-credential-substitute_0.1.7_linux-x86_64.tar.gz"
      sha256 "c09351316b61883fc32b9b95516f873feb35594ea9ff5afc80e18ef2fc75f5be"
    end
  end

  def install
    bin.install "git-credential-substitute"
  end
end
