# This file was generated by GoReleaser. DO NOT EDIT.
class GitCredentialSubstitute < Formula
  desc "git credential helper, which switches git credentials for the username/organization."
  homepage "https://github.com/sadayuki-matsuno/git-credential-substitute"
  version "0.1.9"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/sadayuki-matsuno/git-credential-substitute/releases/download/v0.1.9/git-credential-substitute_0.1.9_macOS-x86_64.tar.gz"
    sha256 "3747883ea5d1f583188a33200c3782b1e50a054f942bb1c7e3e97048d72227fa"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/sadayuki-matsuno/git-credential-substitute/releases/download/v0.1.9/git-credential-substitute_0.1.9_linux-x86_64.tar.gz"
      sha256 "c64b2754d0f7af2f812905c75069e4668a8985ded8a2da170deb9cc52455bc01"
    end
  end

  def install
    bin.install "git-credential-substitute"
  end
end
